language: ruby

cache:
  bundler: true

dist: trusty

before_install:
  - pip install awscli --user

stages:
  - test
  - buld latest archives
  - PHP
  - Python
  - Ruby

jobs:
  include:
    - stage: test
      script: bundle exec rake spec
    - stage: build latest archives
      script: bundle exec rake build_latest_archives
    - script: bundle exec rake build[apt-whitelist-checker,run]
    - stage: PHP
      script: bundle exec rake build[php-src-builder,default,'VERSION=master ALIAS=nightly ICU_RELEASE=59.1 ICU_INSTALL_DIR=$HOME/.phpenv/versions/$VERSION']; sleep 1200
    - script: bundle exec rake build[php-src-builder,default,'VERSION=7.0snapshot ALIAS=$VERSION ICU_RELEASE=59.1 ICU_INSTALL_DIR=$HOME/.phpenv/versions/$VERSION']
    - script: bundle exec rake build[php-src-builder,default,'VERSION=7.1snapshot ALIAS=$VERSION ICU_RELEASE=59.1 ICU_INSTALL_DIR=$HOME/.phpenv/versions/$VERSION']
    - script: bundle exec rake build[php-src-builder,default,'VERSION=7.2snapshot ALIAS=$VERSION ICU_RELEASE=59.1 ICU_INSTALL_DIR=$HOME/.phpenv/versions/$VERSION']
    - stage: Python
    - script: bundle exec rake build[cpython-builder,default,VERSION=3.5-dev]; sleep 1200
    - script: bundle exec rake build[cpython-builder,default,VERSION=3.6-dev]
    - script: bundle exec rake build[cpython-builder,default,VERSION=3.7-dev]
    - script: bundle exec rake build[cpython-builder,default,VERSION=nightly]
    - script: bundle exec rake build['cpython-builder','default','VERSION=pypy3-dev ALIAS=pypy3-nightly']
    - script: bundle exec rake build['cpython-builder','default','VERSION=pypy-dev ALIAS=pypy-nightly']
    - stage: Ruby
      script: bundle exec rake build['travis-rubies','build','RUBY=ruby-head']
    - script: bundle exec rake build['travis-rubies','build','RUBY=jruby-head']
    - script: bundle exec rake build['travis-rubies','build','RUBY=mruby-head']
    - script: bundle exec rake build['travis-rubies','build','RUBY=ruby-head-clang']
