language: ruby

cache:
  bundler: true

dist: trusty

rvm: 2.3.1

before_install:
  - pip install awscli --user

jobs:
  include:
    - stage: test
      script: bundle exec rake spec
    - stage: build latest archives
      script: bundle exec rake build_latest_archives
    - stage: build
      script: bundle exec rake build[apt-whitelist-checker,run]
    - stage: build
      script: bundle exec rake build[php-src-builder,default,'VERSION=master ALIAS=nightly ICU_RELEASE=57.1 ICU_INSTALL_DIR=$HOME/.phpenv/versions/$VERSION']
    - stage: build
      script: bundle exec rake build[php-src-builder,default,'VERSION=7.0snapshot ALIAS=$VERSION ICU_RELEASE=57.1 ICU_INSTALL_DIR=$HOME/.phpenv/versions/$VERSION']
    - stage: build
      script: bundle exec rake build[php-src-builder,default,'VERSION=7.1snapshot ALIAS=$VERSION ICU_RELEASE=57.1 ICU_INSTALL_DIR=$HOME/.phpenv/versions/$VERSION']
    - stage: build
      script: bundle exec rake build[php-src-builder,default,'VERSION=7.2snapshot ALIAS=$VERSION ICU_RELEASE=57.1 ICU_INSTALL_DIR=$HOME/.phpenv/versions/$VERSION']
    - stage: build
      script: bundle exec rake build[cpython-builder]
    - stage: build
      script: bundle exec rake build[cpython-builder,default,VERSION=3.5-dev]
    - stage: build
      script: bundle exec rake build[cpython-builder,default,VERSION=3.6-dev]
    - stage: build
      script: bundle exec rake build['cpython-builder','default','VERSION=pypy3-dev ALIAS=pypy3-nightly']
    - stage: build
      script: bundle exec rake build['cpython-builder','default','VERSION=pypy-dev ALIAS=pypy-nightly']
    - stage: build
      script: bundle exec rake build['travis-rubies','build','RUBY=ruby-head']
    - stage: build
      script: bundle exec rake build['travis-rubies','build','RUBY=jruby-head']
    - stage: build
      script: bundle exec rake build['travis-rubies','build','RUBY=mruby-head']
    - stage: build
      script: bundle exec rake build['travis-rubies','build','RUBY=ruby-head-clang']
