language: ruby

cache:
  bundler: true

dist: trusty

rvm: 2.3.1

jobs:
  include:
    - stage: test
      script: bundle exec rake spec
    - stage: build
      env: ARCHIVE=apt-whitelist-checker
      script: bundle exec rake build[apt-whitelist-checker,run]
    - stage: build
      env: ARCHIVE=php-nightly
      script: bundle exec rake build[php-src-builder,default,'VERSION=master ALIAS=nightly ICU_RELEASE=57.1 ICU_INSTALL_DIR=$HOME/.phpenv/versions/$VERSION']
    - stage: build
      env: ARCHIVE=php-7.0snapshot
      script: bundle exec rake build[php-src-builder,default,'VERSION=7.0snapshot ALIAS=$VERSION ICU_RELEASE=57.1 ICU_INSTALL_DIR=$HOME/.phpenv/versions/$VERSION']
    - stage: build
      env: ARCHIVE=php-7.1snapshot
      script: bundle exec rake build[php-src-builder,default,'VERSION=7.1snapshot ALIAS=$VERSION ICU_RELEASE=57.1 ICU_INSTALL_DIR=$HOME/.phpenv/versions/$VERSION']
    - stage: build
      env: ARCHIVE=cpython
      script: bundle exec rake build[cpython-builder]
    - stage: build
      env: ARCHIVE=python-3.5-dev
      script: bundle exec rake build[cpython-builder,default,VERSION=3.5-dev]
    - stage: build
      env: ARCHIVE=python-3.6-dev
      script: bundle exec rake build[cpython-builder,default,VERSION=3.6-dev]
    - stage: build
      env: ARCHIVE=pypy3-dev
      script: bundle exec rake build['cpython-builder','default','VERSION=pypy3-dev ALIAS=pypy3-nightly']
    - stage: build
      env: ARCHIVE=pypy-dev
      script: bundle exec rake build['cpython-builder','default','VERSION=pypy-dev ALIAS=pypy-nightly']
    - stage: build
      env: ARCHIVE=ruby-head
      script: bundle exec rake build['travis-rubies','build','RUBY=ruby-head']
    - stage: build
      env: ARCHIVE=jruby-head
      script: bundle exec rake build['travis-rubies','build','RUBY=jruby-head']
    - stage: build
      env: ARCHIVE=mruby-head
      script: bundle exec rake build['travis-rubies','build','RUBY=mruby-head']
    - stage: build
      env: ARCHIVE=ruby-head-clang
      script: bundle exec rake build['travis-rubies','build','RUBY=ruby-head-clang']
